# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workload_protocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='workload_protocol.proto',
  package='workload',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x17workload_protocol.proto\x12\x08workload\"l\n\x08ProtoRfw\x12\x12\n\nbench_type\x18\x01 \x02(\t\x12\x12\n\nwl_metrics\x18\x02 \x02(\r\x12\x12\n\nbatch_unit\x18\x03 \x02(\r\x12\x10\n\x08\x62\x61tch_id\x18\x04 \x02(\r\x12\x12\n\nbatch_size\x18\x05 \x02(\r\"\x9b\x01\n\x08ProtoRfd\x12\x0c\n\x04keys\x18\x01 \x03(\t\x12\x32\n\x08workload\x18\x02 \x03(\x0b\x32 .workload.ProtoRfd.ProtoWorkload\x1aM\n\rProtoWorkload\x12\x0b\n\x03\x63pu\x18\x01 \x01(\x05\x12\x0e\n\x06net_in\x18\x02 \x01(\x05\x12\x0f\n\x07net_out\x18\x03 \x01(\x05\x12\x0e\n\x06memory\x18\x04 \x01(\x01')
)




_PROTORFW = _descriptor.Descriptor(
  name='ProtoRfw',
  full_name='workload.ProtoRfw',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bench_type', full_name='workload.ProtoRfw.bench_type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wl_metrics', full_name='workload.ProtoRfw.wl_metrics', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_unit', full_name='workload.ProtoRfw.batch_unit', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_id', full_name='workload.ProtoRfw.batch_id', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='workload.ProtoRfw.batch_size', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=145,
)


_PROTORFD_PROTOWORKLOAD = _descriptor.Descriptor(
  name='ProtoWorkload',
  full_name='workload.ProtoRfd.ProtoWorkload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpu', full_name='workload.ProtoRfd.ProtoWorkload.cpu', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_in', full_name='workload.ProtoRfd.ProtoWorkload.net_in', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='net_out', full_name='workload.ProtoRfd.ProtoWorkload.net_out', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memory', full_name='workload.ProtoRfd.ProtoWorkload.memory', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=303,
)

_PROTORFD = _descriptor.Descriptor(
  name='ProtoRfd',
  full_name='workload.ProtoRfd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='workload.ProtoRfd.keys', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workload', full_name='workload.ProtoRfd.workload', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_PROTORFD_PROTOWORKLOAD, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=303,
)

_PROTORFD_PROTOWORKLOAD.containing_type = _PROTORFD
_PROTORFD.fields_by_name['workload'].message_type = _PROTORFD_PROTOWORKLOAD
DESCRIPTOR.message_types_by_name['ProtoRfw'] = _PROTORFW
DESCRIPTOR.message_types_by_name['ProtoRfd'] = _PROTORFD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoRfw = _reflection.GeneratedProtocolMessageType('ProtoRfw', (_message.Message,), {
  'DESCRIPTOR' : _PROTORFW,
  '__module__' : 'workload_protocol_pb2'
  # @@protoc_insertion_point(class_scope:workload.ProtoRfw)
  })
_sym_db.RegisterMessage(ProtoRfw)

ProtoRfd = _reflection.GeneratedProtocolMessageType('ProtoRfd', (_message.Message,), {

  'ProtoWorkload' : _reflection.GeneratedProtocolMessageType('ProtoWorkload', (_message.Message,), {
    'DESCRIPTOR' : _PROTORFD_PROTOWORKLOAD,
    '__module__' : 'workload_protocol_pb2'
    # @@protoc_insertion_point(class_scope:workload.ProtoRfd.ProtoWorkload)
    })
  ,
  'DESCRIPTOR' : _PROTORFD,
  '__module__' : 'workload_protocol_pb2'
  # @@protoc_insertion_point(class_scope:workload.ProtoRfd)
  })
_sym_db.RegisterMessage(ProtoRfd)
_sym_db.RegisterMessage(ProtoRfd.ProtoWorkload)


# @@protoc_insertion_point(module_scope)
